### ISSUE TITLE
Failure to sync to Monarch after 2/15 update.

### ISSUE THREAD

**Issue by conyerbd** [alex-peck/monarch-amazon-sync#14]
Looks like something broke with the new update Monarch pushed out. Getting the following error when trying to sync.

Fetching Monarch transactions
TypeError: Cannot read properties of undefined (reading 'allTransactions')
    at te (chrome-extension://eafiodpcmkckfdolemicjcihfmaahnoa/src/pages/background/index.js:33:34)
    at async G (chrome-extension://eafiodpcmkckfdolemicjcihfmaahnoa/src/pages/background/index.js:33:3204)
    at async K (chrome-extension://eafiodpcmkckfdolemicjcihfmaahnoa/src/pages/background/index.js:33:1993)

**Comment by msanity** [comment]
Getting the same error:
TypeError: Cannot read properties of undefined (reading 'allTransactions')
    at te (chrome-extension://dmgnmkkbnoljphackmcefkebnjgnjdcd/src/pages/background/index.js:33:34)
    at async G (chrome-extension://dmgnmkkbnoljphackmcefkebnjgnjdcd/src/pages/background/index.js:33:3204)
    at async K (chrome-extension://dmgnmkkbnoljphackmcefkebnjgnjdcd/src/pages/background/index.js:33:1993)

**Comment by acrossen** [comment]
Triple-tapping on this; same error here. Seems to download Amzon transactions fine, errors out as above, then summarizes the error on the home screen:

![image](https://github.com/alex-peck/monarch-amazon-sync/assets/5323238/87820df8-255f-4dc7-b33b-40993d88b113)

**Comment by chipete** [comment]
me too
<img width="321" alt="Screenshot 2024-09-24 at 5 15 27 PM" src="https://github.com/user-attachments/assets/20ebc30e-ba43-43d4-b699-12decdb91a18">

**Comment by aaronbgithub** [comment]
I tried the new 0.3.1 release and I am still getting this error too.  I should mention I tried resetting the monarch connection status multiple times (since this is a new feature in 0.3.1) with no luck.
Here's what the debug log has at the monarch section:
Fetching Monarch transactions
TypeError: Cannot read properties of undefined (reading 'allTransactions')
    at ne (chrome-extension://jomokphpaggkjkaiacjfpgfombgijapo/src/pages/background/index.js:33:34)
    at async G (chrome-extension://jomokphpaggkjkaiacjfpgfombgijapo/src/pages/background/index.js:33:3158)
    at async K (chrome-extension://jomokphpaggkjkaiacjfpgfombgijapo/src/pages/background/index.js:33:2001)
Sync complete
![image](https://github.com/user-attachments/assets/e7b74481-568e-4048-ac4d-75ec6c9e9e53)

UPDATE: 12/10/24 - I am no longer getting this error.  I did nothing.  It just started working.

**Comment by chintito4ever** [comment]
I am getting same error...I see transactions being downloaded but then fails to sync to Monarch...

**Comment by michael-c-williams** [comment]
Thanks for making this extension! I'd gladly buy it.

I'm having the same issue with v0.3.1:

Got order invoice response 200 for order 114-7478550-1408243
Fetching Monarch transactions
TypeError: Cannot read properties of undefined (reading 'allTransactions')
    at ne (chrome-extension://kapginljfhcpigcfcekmkdmcgnhfkcpe/src/pages/background/index.js:33:34)
    at async G (chrome-extension://kapginljfhcpigcfcekmkdmcgnhfkcpe/src/pages/background/index.js:33:3158)
    at async K (chrome-extension://kapginljfhcpigcfcekmkdmcgnhfkcpe/src/pages/background/index.js:33:2001)
Sync complete

**Comment by chintito4ever** [comment]
Update: after installing and uninstalling few times, I see errors gone and working. Not sure what changed!
