### ISSUE TITLE
An error occurred while fetching Monarch transactions

### ISSUE THREAD

**Issue by tjkcc** [alex-peck/monarch-amazon-sync#36]
Thanks for the awesome extension!
Just updated to 0.3.1 and running into this error:

![image](https://github.com/user-attachments/assets/921c51aa-a7eb-415f-967f-f4c1c71ea0f4)

**Comment by jimboca** [comment]
I get the same error, then open the log and after it fetches all Amazon invoices it says:
```
Fetching Monarch transactions
TypeError: Cannot read properties of undefined (reading 'allTransactions')
    at ne (chrome-extension://immlnbnpecghdpbnkmligficdnmchepe/src/pages/background/index.js:33:34)
    at async G (chrome-extension://immlnbnpecghdpbnkmligficdnmchepe/src/pages/background/index.js:33:3158)
    at async K (chrome-extension://immlnbnpecghdpbnkmligficdnmchepe/src/pages/background/index.js:33:2001)
Sync complete
```

**Comment by jimboca** [comment]
I downloaded 0.2.0 and it gives same error, with different line numbers of course.
```
Fetching Monarch transactions
TypeError: Cannot read properties of undefined (reading 'allTransactions')
    at te (chrome-extension://iicbkgmgjoaiapoilpnfnneegpeknmkl/src/pages/background/index.js:33:34)
    at async G (chrome-extension://iicbkgmgjoaiapoilpnfnneegpeknmkl/src/pages/background/index.js:33:3204)
    at async K (chrome-extension://iicbkgmgjoaiapoilpnfnneegpeknmkl/src/pages/background/index.js:33:1993)
Sync complete
```

**Comment by josiah-eichelman** [comment]
I'm also getting the same error. Started happening mid nov I believe

**Comment by aaronbgithub** [comment]
This randomly started working for me.  I am no longer getting this error.

**Comment by jeleffto** [comment]
I'm getting the same error, unfortunately.

**Comment by tjkcc** [comment]
Mine started to sync again 🤷‍♂️

**Comment by jimboca** [comment]
> Mine started to sync again 🤷‍♂️

Which version? 0.3.1 ?

**Comment by tjkcc** [comment]
> > Mine started to sync again 🤷‍♂️
> 
> Which version? 0.3.1 ?

Yes

**Comment by josiah-eichelman** [comment]
I did not realize I was using an outdated extension, once updating everything is working!!

**Comment by mscholtz** [comment]
I'm getting this error too, on the most recent release

**Comment by mattjparkerr** [comment]
Im getting same error, any solutions? 
Fetching Monarch transactions
TypeError: Cannot read properties of undefined (reading 'allTransactions')
    at ne (chrome-extension://abcmdbhlencjiojmmdoejgebeodikkhf/src/pages/background/index.js:33:34)
    at async G (chrome-extension://abcmdbhlencjiojmmdoejgebeodikkhf/src/pages/background/index.js:33:3158)
    at async K (chrome-extension://abcmdbhlencjiojmmdoejgebeodikkhf/src/pages/background/index.js:33:2001)
Sync complete

**Comment by jbiddle88** [comment]
I'm getting this same error on 0.3.1 as well. Any updates on fixing it?

**Comment by kbex9** [comment]
Same, getting error on 0.3.1  :(

**Comment by amberstar** [comment]
This fixed it for me on 0.3.1: Close Monarch, uninstall 0.3.1, reinstall, when you get error log-in to Monarch message, open Monarch.
