### ISSUE TITLE
sync is failing with TypeError, auth is succeeding on both Monarch and Amazon

### ISSUE THREAD

**Issue by ShawnCarnell** [alex-peck/monarch-amazon-sync#38]
Auth is succeeding on both Monarch and Amazon but sync is failing with TypeError.

I have the following debug log:

```
Fetching Amazon orders
Fetching orders from https://www.amazon.com/gp/css/order-history?disableCsd=no-js
TypeError: Failed to fetch
    at sl (chrome-extension://haeepjefheckdejmnalblhobpomnognn/assets/js/types.UWpp-Ndg.js:8:163374)
    at async G (chrome-extension://haeepjefheckdejmnalblhobpomnognn/src/pages/background/index.js:33:2652)
    at async K (chrome-extension://haeepjefheckdejmnalblhobpomnognn/src/pages/background/index.js:33:2001)
    at async chrome-extension://haeepjefheckdejmnalblhobpomnognn/src/pages/background/index.js:33:764
Sync complete
Checking Amazon auth
Got Amazon auth response200
Amazon auth success
```

Any recommendations on things to try? I didn't see any related open issues.

I will try to pull the source uncompressed source and see if I can debug if I get time.

**Comment by ReactionShot** [comment]
Same exact issue when I run it

**Comment by mattjparkerr** [comment]
Getting error when it gets to fetching monarch transactions, seems like the amazon ones come through no problem

Fetching Monarch transactions
TypeError: Cannot read properties of undefined (reading 'allTransactions')
    at ne (chrome-extension://abcmdbhlencjiojmmdoejgebeodikkhf/src/pages/background/index.js:33:34)
    at async G (chrome-extension://abcmdbhlencjiojmmdoejgebeodikkhf/src/pages/background/index.js:33:3158)
    at async K (chrome-extension://abcmdbhlencjiojmmdoejgebeodikkhf/src/pages/background/index.js:33:2001)
Sync complete

**Comment by mattjparkerr** [comment]
Does it matter how you sign into monarch, ie using google sign in vs username/ pass. Does multifactor authentication cause issues with this?

**Comment by ReactionShot** [comment]
I use standard authentication (non-Oauth) and even disabling MFA the app fails at the same point as you showed above (i.e. pulling all Amazon transactions and then failing on Monarch transactions).

**Comment by mattjparkerr** [comment]
hmm, I tried a few things, like uninstalling reinstalling the extension. Trying from both mac/ pc, current version of chrome is up to date. 

Some other say it randomly starts working after some time.. not sure.

**Comment by mattjparkerr** [comment]
So mine randomly started working, I did nothing. No different sign in, same release version, same passwords etc... not sure how this helps anyone.

**Comment by ReactionShot** [comment]
It works for me now as well, not sure what the deal is.  Thanks @mattjparkerr for the heads up!

**Comment by mattjparkerr** [comment]
Interesting, so I set this up one another computer. Same extensions release/ settings getting same error as before. However I believe the other computer with the extension is working.

**Comment by todeasa** [comment]
I am also receiving this error.  2 different machines, clean installs.  Monarch and Amazon connect, "An error occurred while fetching Monarch transactions"

Fetching Monarch transactions
TypeError: Cannot read properties of undefined (reading 'allTransactions')
    at ne (chrome-extension://gedaoleapjklkeeancjkiapaegnddbpi/src/pages/background/index.js:33:34)
    at async G (chrome-extension://gedaoleapjklkeeancjkiapaegnddbpi/src/pages/background/index.js:33:3158)
    at async oe (chrome-extension://gedaoleapjklkeeancjkiapaegnddbpi/src/pages/background/index.js:33:1865)
Sync complete


Happy to help troubleshoot any way I can.

**Comment by mattjparkerr** [comment]
@todeasa idk how this makes sense, however at somepoint the extension will just begin working for mine it took like 2 weeks and randomly started working. I didnt uninstall or change anything. I know not very good advice however patience I guess work somehow.

**Comment by todeasa** [comment]
I got it to work.

- Signed out from Monarch
- Reset Monarch Connection Status
- Removed all On-Device Site Data from Chrome
- Signed back in to Monarch

Sync Worked the first time after this.

Love the extension!! Thanks!

**Comment by dahawk04** [comment]
I am having this issue. I tried all the steps above multiple times without any success. Anyone have other suggestions?
