### ISSUE TITLE
 Getting Error: Sync failed, please try again Failure reason: No Amazon orders found

### ISSUE THREAD

**Issue by txprojects88** [alex-peck/monarch-amazon-sync#6]
Here is the debug logs. Let me know if anything else is needed. Can't wait to get this to work! Thanks!

`<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/seth/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/seth/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Fetching Amazon   orders
--
Fetching orders from   https://www.amazon.com/gp/css/order-history
Got orders response 200
Found 0 orders
Fetching orders from   https://www.amazon.com/gp/css/order-history?startIndex=10
Got orders response 200 for page 2
TypeError: Cannot read properties of   undefined (reading 'trim')
at su.<anonymous>   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:9:20)
at h.Gi [as each]   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:6:11608)
at Ra   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:8:163054)
at w0   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:8:162998)
at async $0   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:8:162486)
at async G   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/src/pages/background/index.js:33:2670)
at async K   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/src/pages/background/index.js:33:1993)
Fetching orders from   https://www.amazon.com/gp/css/order-history?startIndex=20
Got orders response 200 for page 3
TypeError: Cannot read properties of   undefined (reading 'trim')
at su.<anonymous>   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:9:20)
at h.Gi [as each]   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:6:11608)
at Ra   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:8:163054)
at w0   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:8:162998)
at async $0   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:8:162486)
at async G   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/src/pages/background/index.js:33:2670)
at async K   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/src/pages/background/index.js:33:1993)
Fetching orders from   https://www.amazon.com/gp/css/order-history?startIndex=30
Got orders response 200 for page 4
TypeError: Cannot read properties of   undefined (reading 'trim')
at su.<anonymous>   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:9:20)
at h.Gi [as each]   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:6:11608)
at Ra   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:8:163054)
at w0   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:8:162998)
at async $0   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:8:162486)
at async G   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/src/pages/background/index.js:33:2670)
at async K   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/src/pages/background/index.js:33:1993)
Fetching orders from   https://www.amazon.com/gp/css/order-history?startIndex=40
Got orders response 200 for page 5
TypeError: Cannot read properties of   undefined (reading 'trim')
at su.<anonymous>   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:9:20)
at h.Gi [as each]   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:6:11608)
at Ra   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:8:163054)
at w0   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:8:162998)
at async $0   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:8:162486)
at async G   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/src/pages/background/index.js:33:2670)
at async K   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/src/pages/background/index.js:33:1993)
Fetching orders from   https://www.amazon.com/gp/css/order-history?startIndex=50
Got orders response 200 for page 6
TypeError: Cannot read properties of   undefined (reading 'trim')
at su.<anonymous>   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:9:20)
at h.Gi [as each]   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:6:11608)
at Ra   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:8:163054)
at w0   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:8:162998)
at async $0   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/assets/js/types.LCXgyiJn.js:8:162486)
at async G   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/src/pages/background/index.js:33:2670)
at async K   (chrome-extension://ppeaiiegenceemaplnmbpicdjnkpelnn/src/pages/background/index.js:33:1993)
No Amazon orders found
Sync complete

</body>

</html>
`

**Comment by mdo77** [comment]
I got the same thing, whether I'm syncing or doing a dryrun of a backfill.

Logs attached.  Love the potential here!

[error-dump (2).txt](https://github.com/alex-peck/monarch-amazon-sync/files/14024471/error-dump.2.txt)

**Comment by LegitimateOcelot871** [comment]
I have the same bug also.

**Comment by idpaterson** [comment]
When you visit that order page linked in the debug log, is the header of each order formatted as shown below?
<img width="937" alt="Amazon order card header" src="https://github.com/alex-peck/monarch-amazon-sync/assets/507058/61b193c0-b481-43ba-972b-8bdfacdf9f33">

The error is being triggered by some code that expects "ORDER #" followed by the numeric order code in the upper right. It seems like maybe there is no # sign or perhaps the order card layout is different for your orders.

**Comment by aoganezo** [comment]
This is happening to me as well, and clearing cache doesn't work. @idpaterson , while a typical order does seem to look fine, I also have Amazon Fresh orders. It also has the same Order #, but on invoice. That got me thinking that the general containers may be formatted differently, which is why it can't find the order numbers. Haven't dug deeper into it yet though.
Regular:
<img width="951" alt="image" src="https://github.com/alex-peck/monarch-amazon-sync/assets/14896951/c19ca929-d2c9-46ad-8172-0f13875bcc2e">
Fresh:
<img width="939" alt="image" src="https://github.com/alex-peck/monarch-amazon-sync/assets/14896951/31f44c5c-2124-4607-a845-ce674af2cc21">

**Comment by idpaterson** [comment]
I don’t have any Amazon Fresh orders to test but maybe the author of this extension does. If that View Order Details link takes you to a page with `orderID=xxxxx` in the web address then #12 will work to resolve this error. I suspect that there will be other differences on the details page since the code to get transaction details is quite fragile. It’s not quite working for many normal Amazon orders at the moment anyway so hopefully the author has time to review the contributed code fixes.
